custom_application_fields = {
"Application ID":                                    "Application_ID",           
"Students First Name":                               "Students_First_Name",           
"Students Last Name":                                "Students_Last_Name",           
"School Applying to":                                "School_Applying_to",           
"Grade Applying To":                                 "Grade_Applying_To",           
"Application Status":                                "Application_Status",           
"Waitlist Number":                                   "Waitlist_Number",           
"Application Type":                                  "Application_Type",           
"Account ID":                                        "Account_ID",           
"Account Preferred Language":                        "Account_Preferred_Language",           
"Current Grade":                                     "Current_Grade",           
"Enrollment Period":                                 "Enrollment_Period",           
"Submission Date":                                   "Submission_Date",           
"Submitted By":                                      "Submitted_By",           
"Offered Date":                                      "Offered_Date",           
"Accepted Date":                                     "Accepted_Date",           
"Registration Completed Date":                       "Registration_Completed_Date",           
"Last Update Date":                                  "Last_Update_Date",           
"Primary Guardian First Name":                       "Primary_Guardian_First_Name",           
"Primary Guardian Last Name":                        "Primary_Guardian_Last_Name",           
"Primary Guardian Email":                            "Primary_Guardian_Email",           
"Primary Guardian mobile Phone":                     "Primary_Guardian_mobile_Phone",           
"Primary Guardian Home Phone":                       "Primary_Guardian_Home_Phone",           
"Primary Guardian Work Phone":                       "Primary_Guardian_Work_Phone",           
"Secondary Guardian First Name":                     "Secondary_Guardian_First_Name",           
"Secondary Guardian Last Name":                      "Secondary_Guardian_Last_Name",           
"Secondary Guardian Email":                          "Secondary_Guardian_Email",           
"Secondary Guardian mobile Phone":                   "Secondary_Guardian_mobile_Phone",           
"Secondary Guardian Home Phone":                     "Secondary_Guardian_Home_Phone",           
"Secondary Guardian Work Phone":                     "Secondary_Guardian_Work_Phone",           
"Student ID":                                        "Student_ID",           
"Student First Name":                                "Student_First_Name",           
"Student Middle Name":                               "Student_Middle_Name",           
"Student Last Name":                                 "Student_Last_Name",           
"Student Birth Date":                                "Student_Birth_Date",           
"Student Gender":                                    "Student_Gender",           
"Current School":                                    "Current_School",           
"Last Status Change":                                "Last_Status_Change",           
"StudentAddress: Street 1":                          "StudentAddress_Street_1",           
"StudentAddress: Street 2":                          "StudentAddress_Street_2",           
"StudentAddress: City":                              "StudentAddress_City",           
"StudentAddress: State":                             "StudentAddress_State",           
"StudentAddress: Zip":                               "StudentAddress_Zip",           
"StudentAddress: Coordinates":                       "StudentAddress_Coordinates",           
"How did you hear about us":                         "How_did_you_hear_about_us",           
"Student Most Used Language":                        "Student_Most_Used_Language",           
"Student Home Use Language":                         "Student_Home_Use_Language",           
"Home Most Used Language":                           "Home_Most_Used_Language",           
"Extra Language Support":                            "Extra_Language_Support",           
"Individualized Education Program":                  "Individualized_Education_Program",           
"Homeless Shelter":                                  "Homeless_Shelter",           
"NYC Public Housing":                                "NYC_Public_Housing",           
"Unaccompanied Youth":                               "Unaccompanied_Youth",           
"Failing Grade School":                              "Failing_Grade_School",           
"Individualized Education Program School":           "Individualized_Education_Program_School",           
"Individualized Education Program Date":             "Individualized_Education_Program_Date",           
"Special Education Services":                        "Special_Education_Services",           
"Special Education Services - Type":                 "Special_Education_Services2",           
"Health Issues":                                     "Health_Issues",           
"Health Impairments":                                "Health_Impairments",           
"Free/Reduced Lunch":                                "Free_Reduced_Lunch",           
"SNAP/TANF":                                         "SNAP_TANF",                     
"Primary Guardian Relation":                         "Primary_Guardian_Relation",           
"Secondary Guardian Relation":                       "Secondary_Guardian_Relation",           
"Sibling 1 Name":                                    "Sibling_1_Name",           
"Sibling 1 Grade":                                   "Sibling_1_Grade",           
"Sibling 1 School":                                  "Sibling_1_School",           
"Sibling 1 DOB":                                     "Sibling_1_DOB",           
"Sibling 2 Name":                                    "Sibling_2_Name",           
"Sibling 2 Grade":                                   "Sibling_2_Grade",           
"Sibling 2 School":                                  "Sibling_2_School",           
"Sibling 2 DOB":                                     "Sibling_2_DOB",           
"Sibling 3 Name":                                    "Sibling_3_Name",           
"Sibling 3 Grade":                                   "Sibling_3_Grade",           
"Sibling 3 School":                                  "Sibling_3_School",           
"Sibling 3 DOB"   :                                  "Sibling_3_DOB",          
"submission_datetime":                               "submission_date"
}
nan_fields = {
    "Current_Grade": "NA",
    "Current_School": "n/a",
}


