

# Some of the colum names of the schoolmint report are incredibly long, so this map renames these columns
COLUMN_RENAME_MAP = {
    'school_year_4_digit': 'school_year_4_digit',
    'Application_ID': 'Application_ID',
    'SM_Student_ID': 'SM_Student_ID',
    'Application_Student_Id': 'Application_Student_Id',
    'SIS_Student_Id': 'SIS_Student_Id',
    'Students_First_Name': 'Students_First_Name',
    'Students_Last_Name': 'Students_Last_Name',
    'School_Applying_to': 'School_Applying_to',
    'Grade_Applying_To': 'Grade_Applying_To',
    'Application_Status': 'Application_Status',
    'Waitlist_Number': 'Waitlist_Number',
    'Application_Type': 'Application_Type',
    'Account_ID': 'Account_ID',
    'Account_Preferred_Language': 'Account_Preferred_Language',
    'Current_Grade': 'Current_Grade',
    'Enrollment_Period': 'Enrollment_Period',
    'Submission_Date': 'Submission_Date',
    'Submitted_By': 'Submitted_By',
    'Offered_Date': 'Offered_Date',
    'Accepted_Date': 'Accepted_Date',
    'Registration_Completed_Date': 'Registration_Completed_Date',
    'Last_Update_Date': 'Last_Update_Date',
    'Primary_Guardian_First_Name': 'Primary_Guardian_First_Name',
    'Primary_Guardian_Last_Name': 'Primary_Guardian_Last_Name',
    'Primary_Guardian_Email': 'Primary_Guardian_Email',
    'Primary_Guardian_mobile_Phone': 'Primary_Guardian_mobile_Phone',
    'Primary_Guardian_Home_Phone': 'Primary_Guardian_Home_Phone',
    'Primary_Guardian_Work_Phone': 'Primary_Guardian_Work_Phone',
    'Secondary_Guardian_First_Name': 'Secondary_Guardian_First_Name',
    'Secondary_Guardian_Last_Name': 'Secondary_Guardian_Last_Name',
    'Secondary_Guardian_Email': 'Secondary_Guardian_Email',
    'Secondary_Guardian_mobile_Phone': 'Secondary_Guardian_mobile_Phone',
    'Secondary_Guardian_Home_Phone': 'Secondary_Guardian_Home_Phone',
    'Secondary_Guardian_Work_Phone': 'Secondary_Guardian_Work_Phone',
    'Student_ID': 'Student_ID',
    'Student_First_Name': 'Student_First_Name',
    'Student_Middle_Name': 'Student_Middle_Name',
    'Student_Last_Name': 'Student_Last_Name',
    'Student_Birth_Date': 'Student_Birth_Date',
    'Student_Gender': 'Student_Gender',
    'Current_School': 'Current_School',
    'Last_Status_Change': 'Last_Status_Change',
    'StudentAddress_Street_1': 'StudentAddress_Street_1',
    'StudentAddress_Street_2': 'StudentAddress_Street_2',
    'StudentAddress_City': 'StudentAddress_City',
    'StudentAddress_State': 'StudentAddress_State',
    'StudentAddress_Zip': 'StudentAddress_Zip',
    'StudentAddress_Coordinates': 'StudentAddress_Coordinates',
    'District': 'District',
    'How_did_you_hear_about_us': 'How_did_you_hear_about_us',
    'Student_Most_Used_Language': 'Student_Most_Used_Language',
    'Student_Home_Use_Language': 'Student_Home_Use_Language',
    'Home_Most_Used_Language': 'Home_Most_Used_Language',
    'Extra_Language_Support': 'Extra_Language_Support',
    'Individualized_Education_Program': 'Individualized_Education_Program',
    'Homeless_Shelter': 'Homeless_Shelter',
    'NYC_Public_Housing': 'NYC_Public_Housing',
    'Unaccompanied_Youth': 'Unaccompanied_Youth',
    'Failing_Grade_School': 'Failing_Grade_School',
    'Individualized_Education_Program_School': 'Individualized_Education_Program_School',
    'Individualized_Education_Program_Date': 'Individualized_Education_Program_Date',
    'Special_Education_Services': 'Special_Education_Services',
    'Health_Issues': 'Health_Issues',
    'Free_Reduced_Lunch': 'Free_Reduced_Lunch',
    'SNAP_TANF': 'SNAP_TANF',
    'Priorities': 'Priorities',
    'Ethnicities': 'Ethnicities',
    'Primary_Guardian_Relation': 'Primary_Guardian_Relation',
    'Secondary_Guardian_Relation': 'Secondary_Guardian_Relation',
    'Sibling_1_Name': 'Sibling_1_Name',
    'Sibling_1_Grade': 'Sibling_1_Grade',
    'Sibling_1_School': 'Sibling_1_School',
    'Sibling_1_DOB': 'Sibling_1_DOB',
    'Sibling_2_Name': 'Sibling_2_Name',
    'Sibling_2_Grade': 'Sibling_2_Grade',
    'Sibling_2_School': 'Sibling_2_School',
    'Sibling_2_DOB': 'Sibling_2_DOB',
    'Registration_Verified_Date': 'Registration_Verified_Date',
    'In which country was the student born?': 'country_of_birth',
    'When did the student first attend school in the United S...': 'first_attend_school_us',
    'What grade level did the student first attend school in ...': 'first_grade_level_attend_school_us',
    'Has the student ever attended a California public (distr...': 'has_student_ever_attended_california_public_school',
    'Has the student ever attended school outside of the Unit...': 'has_student_ever_attended_school_outside_united_states',
    'Has the student ever experienced interruption in their s...': 'has_student_ever_experienced_interruption_in_schooling',
    'Is the student in Special Education?': 'is_student_in_special_education',
    'Does the student receive speech therapy?': 'is_student_receiving_speech_therapy',
    'Does the student have an Individualized Education Progra...': 'does_student_have_iep',
    'Where do you and the student currently live?': 'where_does_guardian_and_student_live',
    'Is the student in Foster Care?': 'is_student_in_foster_care',
    'If yes, please provide the 19 Digit Foster Case ID.': 'foster_care_case_id',
    'Does the student have Medi-Cal Health Insurance?': 'does_student_have_medical_health_insurance',
    'If the student is eligible for public benefits (Medi-Cal...': 'do_you_auth_kipp_to_release_student_info_for_billing',
    'Select all food allergies that apply:': 'student_food_allergies',
    'Select all medication allergies that apply:': 'student_medication_allergies',
    'Select any other allergies that apply:': 'student_other_allergies',
    'If needed, you can provide more details about the studen...': 'student_allergy_details',
    'If needed, you can provide more details about the studen....1': 'student_medical_condition_details',
    'If needed, you can provide more details about the studen....2': 'student_mental_health_history',
    'Does the student have any medical conditions or concerns...': 'does_student_have_medical_conditions_concerns',
    'Does the student have any mental health or behavioral ne...': 'does_student_have_mental_health_behavioral_needs',
    'Select all medical conditions or concerns that apply:': 'medical_conditions_or_concerns',
    'Select all mental health or behavioral needs that apply:': 'mental_health_or_behavioral_needs',
    'Is there an order regarding educational custody or other...': 'is_there_an_order_regarding_custody_or_other_issues',
    'If yes, please explain. You will be asked to submit  a c...': 'custody_order_or_other_issues_explanation',
    'Which language did the student learn when they first beg...': 'language_learned_when_first_began_to_speak',
    'Which language does the student most frequently speak at...': 'langauge_most_frequently_spoken_at_home',
    'Which language do you (i.e. the parent/guardian) most fr...': 'language_most_frequently_spoken_by_parents',
    'Which language is most often spoken among adults (e.g. p...': 'language_most_often_spoken_among_adults',
    'Policy Holder Name': 'policy_holder_name',
    'Medical Insurance Policy or Identification Number': 'medical_insurance_policy_or_identification_number',
    'Medical Insurance Group Number': 'medical_insurance_group_number',
    'Does the student have any oral health concerns (tooth pa...': 'student_oral_health_concerns',
    'Does the student have any hearing concerns?': 'student_hearing_concerns',
    'Does the student have any vision concerns?': 'student_vision_concerns',
    'When was the last date your student took their medicatio...': 'what_date_did_student_last_take_their_medication',
    'Does the student require any medication, including inhal...': 'does_student_require_any_medication_including_inhaler',
    'Does the student have any allergies? This includes food ...': 'does_student_have_any_allergies',
    'Can you select your specific plan from the options below...': 'select_specific_plan_from_options_below',
    'Can you select your specific Medi-Cal or other Public Pl...': 'select_specific_medi-cal_or_public_plan_from_options_below',
    'If you selected "Other" for Health Insurance, please typ...': 'if_other_selected_type_health_insurance_below',
    'Do you give permission for KIPP to work with your child’...': 'permission_for_kipp_to_work_with_student_health_insurance',
    'Does the student have Medi-Cal or Other Public Plan Heal...': 'does_student_have_medicare_or_other_public_plan_healthcare',
}
