
# Folders for SFTP Transfer
LOCALDIR = "files"
SFTP_SOURCEDIR = "schoolmint"
SM_REPORT_NAME = "Regional Automated Application Data SFTP"

# Paths in Google Cloud Storage
BASE_FILE_NAME = "schoolmint_raw_data"
CURRENT_YEAR_FOLDER = "schoolmint/schoolmint_raw_application_data"
HISTORICAL_FOLDER = "schoolmint/schoolmint_raw_application_data_historical"

# Some of the colum names of the schoolmint report are incredibly long, so this map renames these columns
COLUMN_RENAME_MAP = {
    'school_year_4_digit': 'school_year_4_digit',
    'Application_ID': 'Application_ID',
    'SM_Student_ID': 'SM_Student_ID',
    'Application_Student_Id': 'Application_Student_Id',
    'SIS_Student_Id': 'SIS_Student_Id',
    'Students_First_Name': 'Students_First_Name',
    'Students_Last_Name': 'Students_Last_Name',
    'School_Applying_to': 'School_Applying_to',
    'Grade_Applying_To': 'Grade_Applying_To',
    'Application_Status': 'Application_Status',
    'Waitlist_Number': 'Waitlist_Number',
    'Application_Type': 'Application_Type',
    'Account_ID': 'Account_ID',
    'Account_Preferred_Language': 'Account_Preferred_Language',
    'Current_Grade': 'Current_Grade',
    'Enrollment_Period': 'Enrollment_Period',
    'Submission_Date': 'Submission_Date',
    'Submitted_By': 'Submitted_By',
    'Offered_Date': 'Offered_Date',
    'Accepted_Date': 'Accepted_Date',
    'Registration_Completed_Date': 'Registration_Completed_Date',
    'Last_Update_Date': 'Last_Update_Date',
    'Primary_Guardian_First_Name': 'Primary_Guardian_First_Name',
    'Primary_Guardian_Last_Name': 'Primary_Guardian_Last_Name',
    'Primary_Guardian_Email': 'Primary_Guardian_Email',
    'Primary_Guardian_mobile_Phone': 'Primary_Guardian_mobile_Phone',
    'Primary_Guardian_Home_Phone': 'Primary_Guardian_Home_Phone',
    'Primary_Guardian_Work_Phone': 'Primary_Guardian_Work_Phone',
    'Secondary_Guardian_First_Name': 'Secondary_Guardian_First_Name',
    'Secondary_Guardian_Last_Name': 'Secondary_Guardian_Last_Name',
    'Secondary_Guardian_Email': 'Secondary_Guardian_Email',
    'Secondary_Guardian_mobile_Phone': 'Secondary_Guardian_mobile_Phone',
    'Secondary_Guardian_Home_Phone': 'Secondary_Guardian_Home_Phone',
    'Secondary_Guardian_Work_Phone': 'Secondary_Guardian_Work_Phone',
    'Student_ID': 'Student_ID',
    'Student_First_Name': 'Student_First_Name',
    'Student_Middle_Name': 'Student_Middle_Name',
    'Student_Last_Name': 'Student_Last_Name',
    'Student_Birth_Date': 'Student_Birth_Date',
    'Student_Gender': 'Student_Gender',
    'Current_School': 'Current_School',
    'Last_Status_Change': 'Last_Status_Change',
    'StudentAddress_Street_1': 'StudentAddress_Street_1',
    'StudentAddress_Street_2': 'StudentAddress_Street_2',
    'StudentAddress_City': 'StudentAddress_City',
    'StudentAddress_State': 'StudentAddress_State',
    'StudentAddress_Zip': 'StudentAddress_Zip',
    'StudentAddress_Coordinates': 'StudentAddress_Coordinates',
    'District': 'District',
    'How_did_you_hear_about_us': 'How_did_you_hear_about_us',
    'Student_Most_Used_Language': 'Student_Most_Used_Language',
    'Student_Home_Use_Language': 'Student_Home_Use_Language',
    'Home_Most_Used_Language': 'Home_Most_Used_Language',
    'Extra_Language_Support': 'Extra_Language_Support',
    'Individualized_Education_Program': 'Individualized_Education_Program',
    'Homeless_Shelter': 'Homeless_Shelter',
    'NYC_Public_Housing': 'NYC_Public_Housing',
    'Unaccompanied_Youth': 'Unaccompanied_Youth',
    'Failing_Grade_School': 'Failing_Grade_School',
    'Individualized_Education_Program_School': 'Individualized_Education_Program_School',
    'Individualized_Education_Program_Date': 'Individualized_Education_Program_Date',
    'Special_Education_Services': 'Special_Education_Services',
    'Health_Issues': 'Health_Issues',
    'Free_Reduced_Lunch': 'Free_Reduced_Lunch',
    'SNAP_TANF': 'SNAP_TANF',
    'Priorities': 'Priorities',
    'Ethnicities': 'Ethnicities',
    'Primary_Guardian_Relation': 'Primary_Guardian_Relation',
    'Secondary_Guardian_Relation': 'Secondary_Guardian_Relation',
    'Sibling_1_Name': 'Sibling_1_Name',
    'Sibling_1_Grade': 'Sibling_1_Grade',
    'Sibling_1_School': 'Sibling_1_School',
    'Sibling_1_DOB': 'Sibling_1_DOB',
    'Sibling_2_Name': 'Sibling_2_Name',
    'Sibling_2_Grade': 'Sibling_2_Grade',
    'Sibling_2_School': 'Sibling_2_School',
    'Sibling_2_DOB': 'Sibling_2_DOB',
    'Registration_Verified_Date': 'Registration_Verified_Date',
    'in_which_country_was_the_student_born': 'country_of_birth',
    'when_did_student_first_attend_school_in_US_including_PR': 'first_attend_school_us',
    'what_grade_level_did_student_first_attend_school_in_US_incld_PR': 'first_grade_level_attend_school_us',
    'has_student_attended_a_california_public_school_in_past': 'has_student_ever_attended_california_public_school',
    'has_student_attended_school_outside_of_the_US_or_PR': 'has_student_ever_attended_school_outside_united_states',
    'has_student_experienced_interruption_in_their_schooling': 'has_student_ever_experienced_interruption_in_schooling',
    'is_student_in_special_education': 'is_student_in_special_education',
    'does_student_receive_speech_therapy': 'is_student_receiving_speech_therapy',
    'does_student_have_an_individualized_education_program': 'does_student_have_iep',
    'where_do_you_and_the_student_currently_live': 'where_does_guardian_and_student_live',
    'is_the_student_in_foster_care': 'is_student_in_foster_care',
    '19_digit_foster_case_id': 'foster_care_case_id',
    'does_student_have_medi-cal_health_insurance': 'does_student_have_medi_cal_health_insurance',
    'if_student_is_eligible_for_public_benefits_authorize_KIPP': 'do_you_auth_kipp_to_release_student_info_for_billing',
    'select_all_food_allergies_that_apply': 'student_food_allergies',
    'select_all_medication_allergies_that_apply': 'student_medication_allergies',
    'select_all_other_allergies_that_apply': 'student_other_allergies',
    'provide_more_details_about_students_allergies': 'student_allergy_details',
    'provide_more_details_about_students_medical_conditions': 'student_medical_condition_details',
    'provide_more_details_about_students_mental_health_hist': 'student_mental_health_history',
    'does_student_have_medical_conditions_concerns': 'does_student_have_medical_conditions_concerns',
    'does_student_have_mental_health_behavioral_needs': 'does_student_have_mental_health_behavioral_needs',
    'select_medical_conditions_or_concerns_that_apply': 'medical_conditions_or_concerns',
    'select_all_mental_health_or_behavioral_needs_that_apply': 'mental_health_or_behavioral_needs',
    'which_lang_did_student_learn_when_first_begin_to_speak': 'language_learned_when_first_began_to_speak',
    'which_lang_does_student_most_speak_at_home': 'language_most_frequently_spoken_at_home',
    'which_lang_do_you_guardian_speak_most_with_student': 'language_most_frequently_spoken_by_parents',
    'which_lang_do_adults_speak_at_home': 'language_most_often_spoken_among_adults',
    'policy_holder_name': 'policy_holder_name',
    'medical_insurance_policy_or_identification_number': 'medical_insurance_policy_or_identification_number',
    'medical_insurance_group_number': 'medical_insurance_group_number',
    'does_student_have_oral_health_concerns': 'student_oral_health_concerns',
    'does_student_have_hearing_concerns': 'student_hearing_concerns',
    'does_student_have_vision_concerns': 'student_vision_concerns',
    'when_was_the_last_date_student_took_their_medication': 'what_date_did_student_last_take_their_medication',
    'does_student_require_medication': 'does_student_require_any_medication_including_inhaler',
    'does_student_have_allergies_including_food_seasonal': 'does_student_have_any_allergies',
    'can_you_select_your_plan_from_options_below': 'select_specific_plan_from_options_below',
    'can_you_select_your_medi-cal_or_other_public_plan_below': 'select_specific_medi_cal_or_public_plan_from_options_below',
    'if_selected_other_for_health_insurance_type_below': 'if_other_selected_type_health_insurance_below',
    'do_you_give_permission_for_KIPP_to_work_with_student_insurance_CYBHI': 'permission_for_kipp_to_work_with_student_health_insurance',
    'does_student_have_medi-cal_or_other_health_insurance': 'does_student_have_medi_cal_or_other_public_plan_healthcare',
    'is_there_an_order_regarding_educational_custody_or_other_court_order': 'is_there_an_order_regarding_custody_or_other_issues',
    'If_yes_explain_you_will_be_asked_to_submit_a_legal_docs': 'custody_order_or_other_issues_explanation',
    'does_student_currently_have_medical_insurance': 'does_student_currently_have_medical_insurance'
}
